CREATE TRIGGER [dbo].[AfterInsert]
   ON  [dbo].[DS_NGANH]
   AFTER INSERT
AS
BEGIN
		UPDATE DS_NGANH
		SET DS_NGANH.MANGANH = 'NEW'
		WHERE DS_NGANH.MANGANH = (
				SELECT INSERTED.MANGANH
				FROM INSERTED)
      
END