
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iBRP
{

using System;
    using System.Collections.Generic;
    
public partial class AD_MODULE_PERMISSION
{

    public int ID { get; set; }

    public int ID_FUNC { get; set; }

    public int ID_PER { get; set; }

    public int ID_USER { get; set; }

    public string DESCRIPTION { get; set; }

    public Nullable<int> CREATED_ID { get; set; }

    public Nullable<int> UPDATED_ID { get; set; }

    public Nullable<System.DateTime> CREATED_AT { get; set; }

    public Nullable<System.DateTime> UPDATED_AT { get; set; }

}

}
