
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iBRP
{

using System;
    using System.Collections.Generic;
    
public partial class CHUNGTU
{

    public int KHOA { get; set; }

    public string LOAI { get; set; }

    public string LYDO { get; set; }

    public string PTTT { get; set; }

    public Nullable<System.DateTime> NGAYLAP { get; set; }

    public string SOPHIEU { get; set; }

    public string MAKHO_N { get; set; }

    public string MAKHO_X { get; set; }

    public string MADT { get; set; }

    public Nullable<int> CN_SONGAY { get; set; }

    public Nullable<double> CN_SOTIEN { get; set; }

    public string MANV { get; set; }

    public Nullable<double> THUE_SUAT { get; set; }

    public string HOADON_SO { get; set; }

    public string HOADON_KYHIEU { get; set; }

    public Nullable<System.DateTime> HOADON_NGAY { get; set; }

    public string NG_GIAO { get; set; }

    public string NG_NHAN { get; set; }

    public string GHICHU { get; set; }

    public Nullable<double> TL_CK_HD { get; set; }

    public Nullable<double> SOLUONG { get; set; }

    public Nullable<double> SOTIEN { get; set; }

    public Nullable<double> SOTIEN_CK_MH { get; set; }

    public Nullable<double> SOTIEN_CK_HD { get; set; }

    public Nullable<double> SOTIEN_THUE { get; set; }

    public Nullable<double> THANHTOAN { get; set; }

    public Nullable<int> CREATED_ID { get; set; }

    public Nullable<int> UPDATED_ID { get; set; }

    public Nullable<System.DateTime> CREATED_AT { get; set; }

    public Nullable<System.DateTime> UPDATED_AT { get; set; }

}

}
