
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iBRP
{

using System;
    using System.Collections.Generic;
    
public partial class CHUNGTU_CT
{

    public int KHOA { get; set; }

    public int KHOA_CT { get; set; }

    public Nullable<int> STT { get; set; }

    public string MAHANG { get; set; }

    public double SOLUONG { get; set; }

    public Nullable<double> DONGIA_DM { get; set; }

    public Nullable<double> DONGIA_CT { get; set; }

    public Nullable<double> DONGIA { get; set; }

    public Nullable<double> TL_CK { get; set; }

    public Nullable<double> DONGIA_CK { get; set; }

    public Nullable<double> SOTIEN_CK { get; set; }

    public Nullable<double> THANHTIEN { get; set; }

    public Nullable<double> THANHTIEN_CK { get; set; }

    public Nullable<double> THUE_SUAT { get; set; }

    public Nullable<double> SOTIEN_THUE { get; set; }

    public string SOPHIEU { get; set; }

    public Nullable<int> CREATED_ID { get; set; }

    public Nullable<int> UPDATED_ID { get; set; }

    public Nullable<System.DateTime> CREATED_AT { get; set; }

    public Nullable<System.DateTime> UPDATED_AT { get; set; }

}

}
