//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_HANGHOA
    {
        public string MAHANG { get; set; }
        public string MANGANH { get; set; }
        public string MANHOM { get; set; }
        public string MANHOM1 { get; set; }
        public string MAMAU { get; set; }
        public string MASIZE { get; set; }
        public string TENHANG { get; set; }
        public string TENTAT { get; set; }
        public string DVT { get; set; }
        public Nullable<double> QUIDOI { get; set; }
        public string DVT_LON { get; set; }
        public Nullable<double> TON_MAX { get; set; }
        public Nullable<double> TON_MIN { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<double> VAT_IN { get; set; }
        public Nullable<double> VAT_OUT { get; set; }
        public Nullable<double> GIAMUA { get; set; }
        public Nullable<double> TL_LAI_LE { get; set; }
        public Nullable<double> GIABAN_LE { get; set; }
        public Nullable<double> TL_LAI_SI { get; set; }
        public Nullable<double> GIABAN_SI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> CREATED_ID { get; set; }
        public Nullable<int> UPDATED_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    }
}
