//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_KHO
    {
        public string MAKHO { get; set; }
        public string TENKHO { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string FAX { get; set; }
        public string THUKHO { get; set; }
        public Nullable<int> CREATED_ID { get; set; }
        public Nullable<int> UPDATED_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    }
}
