
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iBRP
{

using System;
    using System.Collections.Generic;
    
public partial class DS_NHOM_1
{

    public string MANHOM1 { get; set; }

    public string MANGANH { get; set; }

    public string MANHOM { get; set; }

    public string MA { get; set; }

    public string TENNHOM1 { get; set; }

    public Nullable<int> CREATED_ID { get; set; }

    public Nullable<int> UPDATED_ID { get; set; }

    public Nullable<System.DateTime> CREATED_AT { get; set; }

    public Nullable<System.DateTime> UPDATED_AT { get; set; }

}

}
