//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBRP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iBRPEntities : DbContext
    {
        public iBRPEntities()
            : base("name=iBRPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AD_USER> AD_USER { get; set; }
        public DbSet<DS_DOITAC> DS_DOITAC { get; set; }
        public DbSet<DS_KHAC> DS_KHAC { get; set; }
        public DbSet<DS_KHAC_CT> DS_KHAC_CT { get; set; }
        public DbSet<DS_KHO> DS_KHO { get; set; }
        public DbSet<DS_MAU> DS_MAU { get; set; }
        public DbSet<DS_NGANH> DS_NGANH { get; set; }
        public DbSet<DS_NHOM> DS_NHOM { get; set; }
        public DbSet<DS_NHOM_1> DS_NHOM_1 { get; set; }
        public DbSet<DS_NV> DS_NV { get; set; }
        public DbSet<DS_SIZE> DS_SIZE { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
