
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iBRP
{

using System;
    using System.Collections.Generic;
    
public partial class V_DS_MAU
{

    public string MAKHAC { get; set; }

    public string MAKHAC_CT { get; set; }

    public string TENKHAC { get; set; }

    public string TENKHAC_CT { get; set; }

}

}
